# Generated by Django 5.0.7 on 2024-07-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pass_address_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pass_copy',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pass_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pass_seria',
        ),
        migrations.RemoveField(
            model_name='user',
            name='permanent_address',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
