# Generated by Django 5.0.7 on 2024-08-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_birthday_user_birth_date_user_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_id_number',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
