# Generated by Django 5.0.7 on 2024-08-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_student_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_id_number',
            field=models.PositiveIntegerField(max_length=100, null=True, unique=True),
        ),
    ]
