# Generated by Django 5.0.7 on 2024-08-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('third_name', models.CharField(max_length=100)),
                ('birth_date', models.PositiveBigIntegerField(default=0)),
                ('student_id_number', models.PositiveIntegerField(default=0)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Nomi')),
                ('discribe', models.TextField(verbose_name="Ma'lumot")),
                ('begin_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False, verbose_name='Xolati')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nomi')),
                ('resident', models.CharField(max_length=50, verbose_name='Ish beruvchi')),
                ('start_data', models.DateTimeField(auto_now=True, verbose_name='Boshlanish vaqti')),
                ('end_data', models.DateTimeField(auto_now=True, verbose_name='Tugash vaqti')),
                ('discribe', models.TextField(verbose_name="Ma'lumot")),
                ('salary', models.BooleanField(default=True, verbose_name='Holati')),
                ('work_time', models.CharField(choices=[('part_time', 'Part time'), ('full_time', 'Full time')], default='part_time', max_length=20, verbose_name='Ish vaqt tartibi')),
                ('status', models.CharField(choices=[('new', 'Moderatsiyada'), ('on_verification', 'Faollashtirildi'), ('inactive', 'Faol emas')], default='new', max_length=20, verbose_name='Xolati')),
                ('status_admin', models.BooleanField(default=False, verbose_name='Admin uchun kurinish statusi')),
                ('organization', models.CharField(max_length=100, verbose_name='Organizatsiya nomi')),
                ('view_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nomi')),
                ('discribe', models.TextField(verbose_name="Ma'lumotlari")),
                ('show_data', models.DateTimeField(auto_now=True, verbose_name='Sharx vaqti')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Korxona nomi')),
                ('inn', models.PositiveIntegerField(verbose_name='INN')),
                ('describe', models.TextField(verbose_name='Korxona xaqida')),
                ('phone', models.PositiveIntegerField(verbose_name='Korxonani telefon raqami')),
            ],
        ),
        migrations.CreateModel(
            name='Rezume',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=50, verbose_name='Ilmiy daraja (Unvon)')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Wish_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
