# Generated by Django 5.0.7 on 2024-08-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_wish_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('third_name', models.CharField(max_length=100)),
                ('birth_date', models.PositiveIntegerField(default=0)),
                ('student_id_number', models.PositiveIntegerField(default=0)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
    ]
