# Generated by Django 5.0.7 on 2024-08-09 11:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='discribe',
            field=ckeditor.fields.RichTextField(verbose_name="Ma'lumot"),
        ),
        migrations.AlterField(
            model_name='job',
            name='discribe',
            field=ckeditor.fields.RichTextField(verbose_name="Ma'lumot"),
        ),
        migrations.AlterField(
            model_name='new',
            name='discribe',
            field=ckeditor.fields.RichTextField(verbose_name="Ma'lumotlari"),
        ),
        migrations.AlterField(
            model_name='organization',
            name='describe',
            field=ckeditor.fields.RichTextField(verbose_name='Korxona xaqida'),
        ),
    ]
