# Generated by Django 5.0.7 on 2024-08-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_apidata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidata',
            name='birth_date',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
