# Generated by Django 5.0.7 on 2024-08-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_alter_apidata_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('data', models.JSONField()),
            ],
        ),
    ]
