# Generated by Django 5.0.7 on 2024-08-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='begin_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
