# Generated by Django 5.0.7 on 2024-08-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_alter_event_begin_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status_admin',
            field=models.BooleanField(default=False, verbose_name='Admin uchun kurinish statusi'),
        ),
    ]
